//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Insurance_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string EmailAddress { get; set; }
        public int Car_Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Dui { get; set; }
        public int Tickets { get; set; }
        public string Coverage { get; set; }
        public Nullable<decimal> Quote { get; set; }
    }
}
